version: '3'
services:
#--- Collector
  openbmp_collector:
    container_name: openbmp_collector
    image: openbmp/collector
    ports:
     - "5000:5000"
    volumes:
     - /config
    environment:
     # - OPENBMP_ADMIN_ID=collector1
     - KAFKA_FQDN=this-host.domain.com
    links:
     - openbmp_kafka:kafka
    volumes:
      - /var/openbmp/config:/config
    sysctls:
      net.ipv4.tcp_keepalive_intvl: 30
      net.ipv4.tcp_keepalive_probes: 5
      net.ipv4.tcp_keepalive_time: 180
#--- Kafka
  openbmp_kafka:
    image: openbmp/kafka
    ports:
     - "2181:2181"
     - "9092:9092"
    environment:
     - KAFKA_FQDN=this-host.domain.com
    volumes:
      - /var/openbmp/kafka:/data/kafka
     #Test
     # /usr/local/kafka/bin/kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --topic openbmp.parsed.unicast_prefix
     #/usr/local/kafka/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic openbmp.parsed.unicast_prefix

#--- Postgres
  openbmp_postgres:
    image: openbmp/postgres
    ports:
     - 5432:5432
     - 9005:9005
     - 8080:8080
    environment:
     - KAFKA_FQDN=this-host.domain.com
     - ENABLE_RPKI=1
     - ENABLE_IRR=1
    volumes:
      - /var/openbmp/config:/config
      - /var/openbmp/postgres/ts:/data/ts
      - /var/openbmp/postgres/main:/data/main
#--- kafka frontend (Optional)
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
       - 9000:9000
    environment:
       - KAFKA_BROKERCONNECT=this-host.domain.com:9092
