#!/bin/bash
# Copyright (c) 2015-2016 Cisco Systems, Inc. and others.  All rights reserved.
#
# OpenBMP/UI Install script
#

# Add build details
touch /usr/local/build-${BUILD_NUMBER}

#
# Install depends
#
apk add  --update iproute2 wget unzip ca-certificates

# --
# -- Nginx X
# --
apk add nginx
adduser -D -u 1000 -g 'www' www
mkdir /www
chown -R www:www /var/lib/nginx
chown -R www:www /www

# Cleanup
rm -rf /var/cache/apk/*


# Extract BMP-UI
cd /www
unzip /tmp/bmpUI.war
rm -f /tmp/bmpUI.war

# --
# -- Clean up
# --
rm -f /tmp/install
