#!/bin/bash
# Copyright (c) 2015-2016 Cisco Systems, Inc. and others.  All rights reserved.
#
# UI and API run script
#
OPENBMP_API_HOST=${OPENBMP_API_HOST:="localhost"}
OPENBMP_API_PORT=${OPENBMP_API_PORT:=8001}

#
# Start common services
#

# Update the etc hosts file
if [[ -f /config/hosts ]]; then
    cat /config/hosts >> /etc/hosts
fi

#
# Update the hostname if localhost to use the docker localhost/gateway address
#
DOCKER_HOST_IP=$(ip route | grep default | head -1 | awk '{ print $3}')

if [[ ${OPENBMP_API_HOST} == "localhost" ]]; then
    OPENBMP_API_HOST="docker-localhost"

elif [[ ${OPENBMP_API_HOST} == "127.0.0.1" ]]; then
    OPENBMP_API_HOST="docker-localhost"

elif [[ ${OPENBMP_API_HOST} == "::1" ]]; then
    OPENBMP_API_HOST="docker-localhost"
fi

# Update the hosts file
echo "$DOCKER_HOST_IP         docker-localhost" >> /etc/hosts

#
# Configure bmpUI API url
#     Updates "http://"+d+":"+e+"/db_rest/v1/"
if [[ ${OPENBMP_API_HOST} == "docker-localhost" ]]; then
    sed -i -r "s/http:\/\/([^:]+):.*\/db_rest\/v1\//http:\/\/\1:${OPENBMP_API_PORT}\/db_rest\/v1\//" /www/scripts/scripts.*.js
else
    sed -i -r "s/http:\/\/.*\/db_rest\/v1\//http:\/\/${OPENBMP_API_HOST}:${OPENBMP_API_PORT}\/db_rest\/v1\//" /www/scripts/scripts.*.js
fi


#
# Start nginx
#
# nginx -s stop
nginx

# for docker, hang around
sleep 3
echo "Running, now tailing /var/log/nginx/error.log..."
tail -f /var/log/nginx/error.log

