#!/bin/bash
# Collector install script
#
#  Copyright (c) 2013-2015 Cisco Systems, Inc. and others.  All rights reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at http://www.eclipse.org/legal/epl-v10.html
#
# Author: Tim Evens <tim@openbmp.org>

#
# Defaults
#


# Disable interactive
export DEBIAN_FRONTEND=noninteractive

# Install base packages
apt-get update

# Install libsasl2-2 to fix "/usr/bin/openbmpd: error while loading shared libraries: libsasl2.so.2: cannot open shared object file: No such file or directory"
apt-get install -y libsasl2-2

# Fix ubuntu docker install
sed -i 's/exit 101/exit 0/' /usr/sbin/policy-rc.d

# General depend install
apt-get -qq install -y wget unzip  libssl1.0.0 libsasl2-2

# --
# -- OpenBMPd collector
# --
# Install the latest openbmpd package
wget --no-check-certificate --auth-no-challenge \
         https://build-jenkins.openbmp.org:8443/job/openbmp-server-ubuntu-trusty/lastSuccessfulBuild/artifact/*zip*/archive.zip

unzip archive.zip
dpkg -i archive/build/deb_package/openbmp*.deb

rm -rf archive.zip archive

# --
# -- Cron scripts
# --

# -- 
# -- Add host entries for reverse PTR lookups
# -- 
if [[ -f /config/hosts ]]; then
    cat /config/hosts >> /etc/hosts
fi

# -- 
# -- Clean up
# -- 
apt-get clean
rm -rf /var/lib/apt/lists/* /var/tmp/*
rm -f /tmp/install
