#!/bin/bash
# All-in-One run script
#
#  Copyright (c) 2013-2015 Cisco Systems, Inc. and others.  All rights reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at http://www.eclipse.org/legal/epl-v10.html
#
# Author: Tim Evens <tievens@openbmp.org>
#
OPENBMP_BUFFER=${OPENBMP_BUFFER:=16}

DOCKER_HOST_IP=$(ip route | grep default | head -1 | awk '{ print $3}')

if [[ ${KAFKA_FQDN:-""} == "" ]]; then
   echo "ERROR: Missing ENV KAFKA_FQDN.  Cannot proceed until you add that in docker run -e KAFKA_FQDN=<...>"
   exit 1
else
    if [[ ${KAFKA_FQDN} == "localhost" ]]; then
        KAFKA_FQDN="docker-localhost"

    elif [[ ${KAFKA_FQDN} == "127.0.0.1" ]]; then
        KAFKA_FQDN="docker-localhost"

    elif [[ ${KAFKA_FQDN} == "::1" ]]; then
        KAFKA_FQDN="docker-localhost"
    fi
fi


if [[ -f /config/openbmpd ]]; then
    source /config/openbmpd
else
    source /etc/default/openbmpd
fi

#
# System info
#
if [[ ${MEM:-""} = "" ]]; then    
    SYS_TOTAL_MEM=$(grep MemTotal /proc/meminfo | awk '{print int($2 / 1000)}')
else
    SYS_TOTAL_MEM=$(($MEM * 1024))
fi

SYS_NUM_CPU=$(grep processor /proc/cpuinfo | wc -l)

# Start services
service rsyslog start
cron


# Update ENV for openbmpd
sed -r -i "s/OPENBMP_BUFFER=.*/OPENBMP_BUFFER=${OPENBMP_BUFFER}/" /etc/default/openbmpd

# Update the hosts file
echo "$DOCKER_HOST_IP         docker-localhost" >> /etc/hosts

# Update the etc hosts file
if [[ -f /config/hosts ]]; then
    cat /config/hosts >> /etc/hosts
fi

# Start openbmpd and wait - openbmpd runs in foreground
pkill openbmpd
/usr/bin/openbmpd -f -l /var/log/openbmpd.log -a ${OPENBMP_ADMIN_ID} -k $KAFKA_FQDN -hi 5 -p 5000 -b ${OPENBMP_BUFFER}

