#!/bin/bash
# MySQL install script
#
#  Copyright (c) 2013-2016 Cisco Systems, Inc. and others.  All rights reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at http://www.eclipse.org/legal/epl-v10.html
#
# Author: Tim Evens <tim@openbmp.org>

#
# Defaults
#
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:="OpenBMP"}
OPENBMP_DB_PASSWORD=${OPENBMP_DB_PASSWORD:="openbmp"}

# Disable interactive
export DEBIAN_FRONTEND=noninteractive

# General depend install
apk add -U ca-certificates
update-ca-certificates

apk add --update wget unzip python openjdk8-jre-base rsyslog

# --
# -- MySQL/MariaDB server
# --

# Install MySQL/MariaDB Server
apk -U upgrade && apk --update add mariadb mariadb-client

# Create the tmpfs for mysql
if [[ ! -e /var/mysqltmp ]]; then
    mkdir /var/mysqltmp
    chown mysql:mysql /var/mysqltmp
fi

ln -s /etc/mysql/my.cnf /etc/mysql/debian.cnf

# Extract the whois.db.gz file
cd /usr/local
gzip -d whois.db.gz

# Download the current OpenBMP schema
wget -O /usr/local/mysql-openbmp-current.db https://raw.githubusercontent.com/OpenBMP/openbmp-mysql-consumer/master/database/mysql-openbmp-current.db

# --
# -- MySQL consumer
# --
cd /tmp
wget https://build-jenkins.openbmp.org:8443/job/openbmp-mysql-consumer/lastSuccessfulBuild/artifact/*zip*/archive.zip

unzip archive.zip
rm -f archive.zip
mv archive/target/openbmp-mysql-consumer-*.jar /usr/local/openbmp-mysql-consumer.jar
rm -rf archive
rm -f archive.zip

# --
# -- Tomcat and API
# --
export TOMCAT_VERSION=7.0.67

# Install Tomcat
wget "https://archive.apache.org/dist/tomcat/tomcat-7/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz"
gunzip apache-tomcat-${TOMCAT_VERSION}.tar.gz
tar -xf apache-tomcat-${TOMCAT_VERSION}.tar -C /usr
rm apache-tomcat-${TOMCAT_VERSION}.tar
ln -s /usr/apache-tomcat-${TOMCAT_VERSION} /var/lib/tomcat7
rm -rf /usr/tomcat/webapps/examples /usr/tomcat/webapps/docs

# Update the tomcat files
mv /tmp/tomcat7 /etc/default/
rm -rf /var/lib/tomcat7/webapps/ROOT/*
sed -i 's/8080/8001/g' /var/lib/tomcat7/conf/server.xml

# Extract and install DB rest
wget https://build-jenkins.openbmp.org:8443/job/openbmp-db_rest/lastSuccessfulBuild/artifact/*zip*/archive.zip

unzip archive.zip
rm -f archive.zip
mv archive/target/db_rest.war /tmp/
rm -rf archive
mkdir -p /var/lib/tomcat7/webapps/db_rest
cd /var/lib/tomcat7/webapps/db_rest
unzip /tmp/db_rest.war
chown -R tomcat7:tomcat7 /var/lib/tomcat7/webapps/db_rest
cd /tmp
rm -f /tmp/db_rest.war


# configure DB_REST
sed -r -i "s/username=\"[^\"]+\"/username=\"openbmp\"/" /var/lib/tomcat7/webapps/db_rest/META-INF/context.xml
sed -r -i "s/password=\"[^\"]+\"/password=\"${OPENBMP_DB_PASSWORD}\"/" /var/lib/tomcat7/webapps/db_rest/META-INF/context.xml
sed -r -i "s/jdbc:mysql:[^\"]+/jdbc:mysql:\/\/localhost:3306\/openBMP\//" /var/lib/tomcat7/webapps/db_rest/META-INF/context.xml


# --
# -- Cron scripts
# --
cd /tmp
wget https://raw.githubusercontent.com/OpenBMP/openbmp-mysql-consumer/master/cron_scripts/gen-asn-stats/gen-asn-stats.py
wget https://raw.githubusercontent.com/OpenBMP/openbmp-mysql-consumer/master/cron_scripts/db-maint/openbmp-db-maint
wget https://raw.githubusercontent.com/OpenBMP/openbmp-mysql-consumer/master/cron_scripts/gen-whois/dbAccess.py
wget https://raw.githubusercontent.com/OpenBMP/openbmp-mysql-consumer/master/cron_scripts/gen-whois/gen-whois-route.py
mv openbmp-db-maint /etc/periodic/weekly/
chmod 755 /etc/periodic/weekly/openbmp-db-maint
mv gen-asn-stats.py /usr/bin/
chmod 755 /usr/bin/gen-asn-stats.py
mkdir /usr/local/whois
mv dbAccess.py gen-whois-route.py /usr/local/whois/
chmod 755 /usr/local/whois/*
echo "*/30 *  * * *   root   OPENBMP_DB_USER=openbmp OPENBMP_DB_PASSWORD=${OPENBMP_DB_PASSWORD} OPENBMP_DB_NAME=openBMP /usr/bin/gen-asn-stats.py > /var/log/gen-asn-stats.log" >> /etc/crontab
echo "2 17 * * * root /usr/local/whois/gen-whois-route.py -u openbmp -p ${OPENBMP_DB_PASSWORD} -d openBMP localhost  > /var/log/openbmp-whois-route.log" >> /etc/crontab


# --
# -- Clean up
# --
rm -rf /tmp/src && \
rm -rf /var/cache/apk/*
rm -f /tmp/install
